### ISSUE TITLE
purpose of this repository

### ISSUE THREAD

**Issue by ukos-git** [mdengler/scanbd#4]
what is the purpose of this repository? - It is obviously not updated to upstream and not an official scanbd repo.

**Comment by mdengler** [comment]
it was at one point; thanks for your issue #3 last week

**Comment by ukos-git** [comment]
I don‘t like sourceforge and the repo there is also not very active.

**Comment by mdengler** [comment]
Sorry for being unclear; to clarify:

> what is the purpose of this repository?

It is my fork to mirror upstream when I was actively using `scanbd`.

> It is obviously not updated to upstream

Correct.  It was at one point, when I was actively using `scanbd`.

> It [is] not an official scanbd repo.

Correct.

**Comment by mdengler** [comment]
If you are actively using scanbd, you could fork this repo or start anew and I'd be happy to contribute patches, etc.
